# Generated by Django 6.0.1 on 2026-02-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='comment',
            field=models.CharField(default='nothing', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(default='nothing', max_length=255),
        ),
    ]
